/**
 * @file
 * @author University of Warwick
 * @version 1.0
 *
 * @section LICENSE
 *
 * @section DESCRIPTION
 *
 * Description
 *
 * Contains declarations for the DistributionConfigNormal Class
 */

#ifndef CUPCFD_DISTRIBUTIONS_DISTRIBUTION_CONFIG_UNIFORM_INCLUDE_H
#define CUPCFD_DISTRIBUTIONS_DISTRIBUTION_CONFIG_UNIFORM_INCLUDE_H

// Error Codes
#include "Error.h"

// Base Class
#include "DistributionConfig.h"

namespace cupcfd
{
	namespace distributions
	{
		template <class I, class T>
		class DistributionConfigUniform : public DistributionConfig<I,T>
		{
			public:
				// === Members ===

				/** Range Lower Bound (Inclusive) **/
				T lbound;

				/** Range Upper Bound (Non-Inclusive) **/
				T ubound;

				// === Constructors/Deconstructors ===

				/**
				 * Constructor:
				 * Initialises all values to zero.
				 */
				DistributionConfigUniform();

				/**
				 * Constructor:
				 * Initialises values to provided parameters
				 *
				 * @param lbound The lower bound of the distribution range (inclusive)
				 * @param ubound The upper bound of the distribution range (non-inclusive)
				 */
				DistributionConfigUniform(T lbound, T ubound);

				/**
				 * Constructor:
				 * Initialises all values to copies of values from
				 * another configuration.
				 */
				DistributionConfigUniform(DistributionConfigUniform<I,T>& source);

				/**
				 * Deconstructor:
				 * Currently does nothing.
				 */
				virtual ~DistributionConfigUniform();

				// === Concrete Methods ===

				/**
				 * Get the lower bound in the configuration.
				 *
				 * @tparam The data type of the values that might be generated by a distribution.
				 *
				 * @return The lower bound value stored in the configuration.
				 */
				T getLBound();

				/**
				 * Set the lower bound stored in the configuration.
				 *
				 * @param lbound The lower bound value to set the configuration to.
				 *
				 * @tparam The data type of the values that might be generated by a distribution.
				 *
				 * @return Nothing.
				 */
				void setLBound(T lbound);

				/**DistributionConfigUniform
				 * Get the upper bound in the configuration.
				 *
				 * @tparam The data type of the values that might be generated by a distribution.
				 *
				 * @return The upper bound value stored in the configuration.
				 */
				T getUBound();

				/**
				 * Set the upper bound stored in the configuration.
				 *
				 * @param ubound The upper bound value to set the configuration to.
				 *
				 * @tparam The data type of the values that might be generated by a distribution.
				 *
				 * @return Nothing.
				 */
				void setUBound(T ubound);

				void operator=(const DistributionConfigUniform<I,T>& source);
				DistributionConfigUniform<I,T> * clone();
				cupcfd::error::eCodes buildDistribution(Distribution<I,T> ** dist);
		};
	}
}

// Include Header Level Definitions
#include "DistributionConfigUniform.ipp"

#endif
