/**
 * @file
 * @author University of Warwick
 * @version 1.0
 *
 * @section LICENSE
 *
 * @section DESCRIPTION
 *
 * Description
 *
 * Contains declarations for the DistributionConfigSourceUniform Class
 */

#ifndef CUPCFD_DISTRIBUTIONS_DISTRIBUTION_CONFIG_SOURCE_UNIFORM_INCLUDE_H
#define CUPCFD_DISTRIBUTIONS_DISTRIBUTION_CONFIG_SOURCE_UNIFORM_INCLUDE_H

// Error Codes
#include "Error.h"

#include "DistributionConfigSource.h"

namespace cupcfd
{
	namespace distributions
	{
		/**
		 * General Interface for retrieving information from a Distribution config data source
		 * for DistributionConfigUniform objects.
		 *
		 * @tparam The datatype of any indexing scheme used by the distribution
		 * @tparam The datatype of the values generated by the distribution
		 */
		template <class I, class T>
		class DistributionConfigSourceUniform : public DistributionConfigSource<I,T>
		{
			public:
				// === Members ===

				// === Constructors/Deconstructors ===

				/**
				 * Default Constructor
				 *
				 * @tparam The datatype of any indexing scheme used by the distribution
				 * @tparam The datatype of the values generated by the distribution
				 */
				DistributionConfigSourceUniform();

				/**
				 * Constructor:
				 * Copy values from source to this newly constructed object
				 *
				 * @tparam The datatype of any indexing scheme used by the distribution
				 * @tparam The datatype of the values generated by the distribution
				 */
				DistributionConfigSourceUniform(const DistributionConfigSourceUniform<I,T>& source);

				/**
				 * Deconstructor:
				 *
				 * @tparam The datatype of any indexing scheme used by the distribution
				 * @tparam The datatype of the values generated by the distribution
				 */
				virtual ~DistributionConfigSourceUniform();

				// === Concrete Methods ===

				__attribute__((warn_unused_result))
				virtual cupcfd::error::eCodes buildDistributionConfig(DistributionConfig<I,T> ** distConfig) = 0;

				// === Pure Virtual Methods ===
				virtual DistributionConfigSourceUniform<I,T> * clone() = 0;

				/**
				 * Get the Lower Bound Uniform Distribution Configuration Parameter
				 *
				 * @param lBound A pointer to where the retrieved value, if found, will be stored
				 *
				 * @tparam The datatype of any indexing scheme used by the distribution
				 * @tparam The datatype of the values generated by the distribution
				 *
				 * @return An error status indicating the success or failure of the operation
				 * @retval cupcfd::error::E_SUCCESS Success
				 * @retval cupcfd::error::E_CONFIG_OPT_NOT_FOUND No data source was found that specifies the partitioner ID
				 * or is improperly formatted
				 * @retval cupcfd::error::E_CONFIG_INVALID_VALUE A suitable data source was found, but not with a valid value
				 */
				__attribute__((warn_unused_result))
				virtual cupcfd::error::eCodes getLBound(T * lBound) = 0;

				/**
				 * Get the Upper Bound Uniform Distribution Configuration Parameter
				 *
				 * @param lBound A pointer to where the retrieved value, if found, will be stored
				 *
				 * @tparam The datatype of any indexing scheme used by the distribution
				 * @tparam The datatype of the values generated by the distribution
				 *
				 * @return An error status indicating the success or failure of the operation
				 * @retval cupcfd::error::E_SUCCESS Success
				 * @retval cupcfd::error::E_CONFIG_OPT_NOT_FOUND No data source was found that specifies the partitioner ID
				 * or is improperly formatted
				 * @retval cupcfd::error::E_CONFIG_INVALID_VALUE A suitable data source was found, but not with a valid value
				 */
				__attribute__((warn_unused_result))
				virtual cupcfd::error::eCodes getUBound(T * uBound) = 0;
		};
	}
}

// Include Header Level Definitions
#include "DistributionConfigSourceUniform.ipp"

#endif
